# Generated by Django 2.2.7 on 2019-12-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateBaseUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czk', models.DecimalField(decimal_places=5, max_digits=10)),
                ('pln', models.DecimalField(decimal_places=5, max_digits=10)),
                ('eur', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
